module Stopwords
    using WordTokenizers
    using Languages

    customRomanianStopwords = ["vreo", "acelea", "câtă", "cîtă", "degrabă", "lor", "altă", "tot", "ai", "dat", "despre", "peste", "bine", "dar", "foarte", "avea", "mulți", "cît", "cât", "alt", "mai", "să", "fie", "tu", "multe", "orice", "dintr", "dintre", "dintr-o", "dintr-un", "se", "într", "într-o", "într-un", "niște", "multă", "însă", "îl", "fost", "a", "abia", "nimic", "sub", "acel", "în", "altceva", "și", "avem", "altfel", "c", "ea", "acest", "li", "parcă", "fi", "dintre", "unele", "m", "acestei", "mare", "cel", "este", "pe", "atîția", "atâția", "uneori", "acela", "îți", "astăzi", "acestui", "o", "îmi", "ele", "ceilalți", "păi", "față", "nouă", "să-ți", "altul", "au", "i", "prin", "conform", "aceste", "anume", "azi", "k", "unul", "ăla", "unei", "fără", "ei", "la", "aceeași", "u", "înapoi", "acestea", "acesta", "această", "către", "sale", "asupra", "aș", "aceea", "ba", "ale", "da", "le", "apoi", "aia", "suntem", "cum", "își", "înainte", "s", "de", "cînd", "când", "cumva", "chiar", "aceștia", "dacă", "sunt", "care", "al", "numai", "cui", "sus", "tocmai", "prea", "cu", "mi", "eu", "doar", "niciodată", "exact", "puțini", "aiurea", "tuturor", "celor", "astfel", "atunci", "cîteva", "câteva", "cât", "sau", "fel", "între", "acolo", "noștri", "mă", "mult", "una", "ceea", "iar", "sîntem", "suntem", "ați", "din", "geaba", "săi", "căruia", "adică", "încă", "are", "aici", "că", "ia", "nici", "d", "oricum", "asta", "cărora", "face", "cîțiva", "câțiva", "voi", "unor", "f", "atât", "toată", "alături", "cea", "nu", "totuși", "ce", "alțîi", "acum", "sînt", "sunt", "capăt", "mod", "deasupra", "cam", "vom", "b", "toate", "căreia", "această", "atît", "atât", "nimeni", "ii", "ci", "unde", "ul", "plus", "era", "să-mi", "l", "spre", "după", "nou", "cele", "acea", "un", "încît", "încât", "n", "cei", "or", "va", "deci", "același", "atâtea", "h", "vor", "decît", "decât", "noi", "cineva", "deși", "ceva", "j", "ului", "atîtea", "atâtea", "avut", "ar", "pînă", "până", "t", "atâta", "unui", "el", "citi", "așa", "totul", "pentru", "atîta", "v", "alți", "asemenea", "atâția", "te", "ne", "deja", "unii", "p", "atare", "cîte", "câte", "cine", "când", "toți", "vreun", "ori", "r", "alte", "lui", "ți", "ni", "aceia", "am"]
    romanian = union(Set(customRomanianStopwords), Set(stopwords(Languages.English()))) |> words -> [words...]
    english = stopwords(Languages.English()) 
    export romanian, english
end
